### ISSUE TITLE
determine why our routing/network dataset can only be added through arc/catalog

### ISSUE THREAD

**Issue by tbuckl** [MetropolitanTransportationCommission/RegionalTransitDatabase#16]
```
network = C:\\temp\\RegionalTransitDatabase\\data\\TomTom_2015_12_NW.gdb\\TomTom_2015_12_NW.gdb\\Routing\\Routing_ND"

arcpy.na.MakeRouteLayer(network, "WorkRoute", "TravelTime")
```

throws the following error:
```
Runtime error  Traceback (most recent call last):   File "<string>", line 1, in <module>   File "c:\program files (x86)\arcgis\desktop10.4\arcpy\arcpy\na.py", line 1280, in MakeRouteLayer     raise e ExecuteError: ERROR 000732: Input Analysis Network: Dataset C:\temp\RegionalTransitDatabase\data\TomTom_2015_12_NW.gdb\TomTom_2015_12_NW.gdb\Routing\Routing_ND does not exist or is not supported 
```
or, if executed on the data through the toolbox dialog:
```
ExecuteError: ERROR 030033: Parameter does not contain a network dataset data element.  
```

Adding the network dataset by dragging it from Catalog to the TOC makes it available for use. Arc puts up a dialog titled `Adding Network Dataset`, which indicates that there is some special subset of the arcpy Layer adding tool that should allow us to add the network dataset to the mxd. But in my effort to use that tool I hit the same as the first error above, and I can't seem to find a tool in the na.py arcpy tool that would allow us to validate this network dataset or do any kind of introspection on it. 

So for now, we'll just have to manually drag things from catalog into the TOC.

**Comment by tbuckl** [comment]
looks like this was because the .gdb was doubled up in a folder /x.gdb/x.gdb
